name: Jules
on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  jules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Jules
        if: ${{ contains(fromJSON('["hankyuwang"]'), github.event.issue.user.login) }}
        uses: google-labs-code/jules-action@v0.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
